### ISSUE TITLE
When try to convert efficientdet

### ISSUE THREAD

**Issue by waheed0332** [gouthamvgk/coreml_conversion_hub#2]
308/828: Converting Node Type BatchNormalization
309/828: Converting Node Type Conv
310/828: Converting Node Type BatchNormalization
311/828: Converting Node Type Mul
312/828: Converting Node Type Resize
Traceback (most recent call last):
  File "convert_effdet.py", line 65, in <module>
    minimum_ios_deployment_target='13')
  File "/home/waheed/Desktop/venv/lib/python3.6/site-packages/onnx_coreml/converter.py", line 627, in convert
    _convert_node_nd(builder, node, graph, err)
  File "/home/waheed/Desktop/venv/lib/python3.6/site-packages/onnx_coreml/_operators_nd.py", line 2389, in _convert_node_nd
    return converter_fn(builder, node, graph, err)
  File "/home/waheed/Desktop/venv/lib/python3.6/site-packages/onnx_coreml/_operators_nd.py", line 1738, in _convert_resize
    mode=mode
  File "/home/waheed/Desktop/venv/lib/python3.6/site-packages/coremltools/models/neural_network/builder.py", line 1454, in add_upsample
    spec_layer_params.scalingFactor.append(scaling_factor_h)
TypeError: 2.0 has type numpy.float32, but expected one of: int, long

**Comment by waheed0332** [comment]
@gouthamvgk any update on this?

**Comment by gouthamvgk** [comment]
> @gouthamvgk any update on this?

This is due to a bug in onnx_coreml and coremltools version mentioned in requirements. Solution for this is already provided in the convert_effdet.py. You can refer to this comments  https://github.com/gouthamvgk/coreml_conversion_hub/blob/4acf3bc5c5110ffbf0407e986a3b435e3020cf98/pytorch/detection/efficientDet/convert_effdet.py#L15-L19 and change the source code appropriately
